### ISSUE TITLE
Client Certificate is only valid for 14 days

### ISSUE THREAD

**Issue by peddermaster2** [cpw/serverpacklocator#1]
https://github.com/cpw/serverpacklocator/blob/236353b8d50ebf35aab0c613d9cc1b93ec613ddf/src/main/java/cpw/mods/forge/serverpacklocator/cert/CertSigner.java#L24

The client certificate generated by the server is only valid for 14 days.  
It may be better to have a slightly longer time to improve the user experience.

**Comment by cpw** [comment]
fixed
