### ISSUE TITLE
A problem occurred evaluating root project 'serverpacklocator'. > Cannot invoke method head() on null object

### ISSUE THREAD

**Issue by willian420** [cpw/serverpacklocator#2]
i donwloaded the zip file and extract, then i opened a cmd on the extracted folder then runed this command, gradlew build like i always do on some github mods but recived this error on cmd

E:\serverpacklocator-master\serverpacklocator-2.2.0>gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\serverpacklocator-master\serverpacklocator-2.2.0\build.gradle' line: 67

* What went wrong:
A problem occurred evaluating root project 'serverpacklocator'.
> Cannot invoke method head() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by cpw** [comment]
This is not a mod.

**Comment by elainegorogoro** [comment]
This might still be an issue for future releases; cloning this repo doesn't result in this error, but building a downloaded release does.
I don't know what 'grgit' does exactly, but it looks like it pulls local git data, which seem to be missing in release zip files.
