### ISSUE TITLE
Just a question about the locator.

### ISSUE THREAD

**Issue by captinalex1** [cpw/serverpacklocator#7]
My question is, which version under tags is made for Minecraft 1.12.2? Thanks. ^w^

**Comment by MichaelHillcox** [comment]
https://github.com/cpw/serverpacklocator/blob/1.0.0/build.gradle#L53
None from the looks of things. Update to a newer forge version

**Comment by captinalex1** [comment]
I see, wasn't sure. Thanks. ^^
